// <auto-generated />
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(TMSDBContext))]
    partial class TMSDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataLayer.Model.Carrier", b =>
                {
                    b.Property<int>("cID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FTLA")
                        .HasColumnType("int");

                    b.Property<double>("FTLARate")
                        .HasColumnType("double");

                    b.Property<int>("LTLA")
                        .HasColumnType("int");

                    b.Property<double>("LTLRate")
                        .HasColumnType("double");

                    b.Property<string>("cName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("reefCharge")
                        .HasColumnType("double");

                    b.HasKey("cID");

                    b.ToTable("Carrier");

                    b.HasData(
                        new
                        {
                            cID = 1,
                            FTLA = 50,
                            FTLARate = 5.21,
                            LTLA = 640,
                            LTLRate = 0.36209999999999998,
                            cName = "Planet Express",
                            dCity = "Windsor",
                            reefCharge = 0.080000000000000002
                        },
                        new
                        {
                            cID = 2,
                            FTLA = 50,
                            FTLARate = 5.21,
                            LTLA = 640,
                            LTLRate = 0.36209999999999998,
                            cName = "Planet Express",
                            dCity = "Hamilton",
                            reefCharge = 0.080000000000000002
                        },
                        new
                        {
                            cID = 3,
                            FTLA = 50,
                            FTLARate = 5.21,
                            LTLA = 640,
                            LTLRate = 0.36209999999999998,
                            cName = "Planet Express",
                            dCity = "Oshawa",
                            reefCharge = 0.080000000000000002
                        },
                        new
                        {
                            cID = 4,
                            FTLA = 50,
                            FTLARate = 5.21,
                            LTLA = 640,
                            LTLRate = 0.36209999999999998,
                            cName = "Planet Express",
                            dCity = "Belleville",
                            reefCharge = 0.080000000000000002
                        },
                        new
                        {
                            cID = 5,
                            FTLA = 50,
                            FTLARate = 5.21,
                            LTLA = 640,
                            LTLRate = 0.36209999999999998,
                            cName = "Planet Express",
                            dCity = "Ottawa",
                            reefCharge = 0.080000000000000002
                        },
                        new
                        {
                            cID = 6,
                            FTLA = 18,
                            FTLARate = 5.0499999999999998,
                            LTLA = 98,
                            LTLRate = 0.34339999999999998,
                            cName = "Schooner's",
                            dCity = "London",
                            reefCharge = 0.070000000000000007
                        },
                        new
                        {
                            cID = 7,
                            FTLA = 18,
                            FTLARate = 5.0499999999999998,
                            LTLA = 98,
                            LTLRate = 0.34339999999999998,
                            cName = "Schooner's",
                            dCity = "Toronto",
                            reefCharge = 0.070000000000000007
                        },
                        new
                        {
                            cID = 8,
                            FTLA = 18,
                            FTLARate = 5.0499999999999998,
                            LTLA = 98,
                            LTLRate = 0.34339999999999998,
                            cName = "Schooner's",
                            dCity = "Kingston",
                            reefCharge = 0.070000000000000007
                        },
                        new
                        {
                            cID = 9,
                            FTLA = 24,
                            FTLARate = 5.1100000000000003,
                            LTLA = 35,
                            LTLRate = 0.30120000000000002,
                            cName = "Tillman Transport",
                            dCity = "Windsor",
                            reefCharge = 0.089999999999999997
                        },
                        new
                        {
                            cID = 10,
                            FTLA = 18,
                            FTLARate = 5.1100000000000003,
                            LTLA = 45,
                            LTLRate = 0.30120000000000002,
                            cName = "Tillman Transport",
                            dCity = "London",
                            reefCharge = 0.089999999999999997
                        },
                        new
                        {
                            cID = 11,
                            FTLA = 18,
                            FTLARate = 5.1100000000000003,
                            LTLA = 45,
                            LTLRate = 0.30120000000000002,
                            cName = "Tillman Transport",
                            dCity = "Hamilton",
                            reefCharge = 0.089999999999999997
                        },
                        new
                        {
                            cID = 12,
                            FTLA = 11,
                            FTLARate = 5.2000000000000002,
                            LTLA = 0,
                            LTLRate = 0.0,
                            cName = "We Haul",
                            dCity = "Ottawa",
                            reefCharge = 0.065000000000000002
                        },
                        new
                        {
                            cID = 13,
                            FTLA = 11,
                            FTLARate = 5.2000000000000002,
                            LTLA = 0,
                            LTLRate = 0.0,
                            cName = "We Haul",
                            dCity = "Toronto",
                            reefCharge = 0.065000000000000002
                        });
                });

            modelBuilder.Entity("DataLayer.Model.Login", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Username");

                    b.ToTable("Login");

                    b.HasData(
                        new
                        {
                            Username = "admin",
                            Password = "admin",
                            Role = "admin"
                        },
                        new
                        {
                            Username = "planner",
                            Password = "planner",
                            Role = "planner"
                        },
                        new
                        {
                            Username = "buyer",
                            Password = "buyer",
                            Role = "buyer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
